Rscript -e  "install.packages(\"BiocManager\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "install.packages(\"htmltools\", type=\"source\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "install.packages(\"curl\", type=\"binary\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "install.packages(\"progress\", type=\"binary\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "install.packages(\"xml2\", type=\"binary\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "install.packages(\"openssl\", type=\"binary\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "install.packages(\"readxl\", type=\"binary\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "install.packages(\"vroom\", type=\"binary\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "install.packages(\"httr\", type=\"binary\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "install.packages(\"gargle\", type=\"binary\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "install.packages(\"readr\", type=\"binary\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "install.packages(\"googledrive\", type=\"binary\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "install.packages(\"googlesheets4\", type=\"binary\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "install.packages(\"haven\", type=\"binary\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "install.packages(\"rjson\", type=\"binary\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "install.packages(\"tidyverse\", type=\"binary\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "install.packages(\"Hmisc\", type=\"binary\", repos=\"https://cloud.r-project.org/\")"

Rscript -e  "BiocManager::install(\"zlibbioc\", type=\"binary\")"
Rscript -e  "install.packages(\"XML\", type=\"binary\", repos=\"https://cloud.r-project.org/\")"
Rscript -e  "BiocManager::install(\"RCurl\", type=\"binary\")"
Rscript -e  "BiocManager::install(\"GenomeInfoDb\", type=\"binary\")"
Rscript -e  "BiocManager::install(\"GenomeInfoDbData\", type=\"source\")"
Rscript -e  "BiocManager::install(\"XVector\", type=\"binary\")"
Rscript -e  "BiocManager::install(\"Biostrings\", type=\"binary\")"
Rscript -e  "BiocManager::install(\"GenomicRanges\", type=\"binary\")"
Rscript -e  "BiocManager::install(\"KEGGREST\", type=\"binary\")"
Rscript -e  "BiocManager::install(\"SummarizedExperiment\", type=\"binary\")"
Rscript -e  "BiocManager::install(\"AnnotationDbi\", type=\"binary\")"
Rscript -e  "BiocManager::install(\"annotate\", type=\"binary\")"
Rscript -e  "BiocManager::install(\"genefilter\", type=\"binary\")"
Rscript -e  "BiocManager::install(\"geneplotter\", type=\"binary\")"
Rscript -e  "BiocManager::install(\"fgsea\", type=\"binary\")"


Rscript -e  "BiocManager::install(\"data.table\", type=\"source\")"
Rscript -e  "BiocManager::install(\"circlize\", type=\"source\")"
Rscript -e  "BiocManager::install(\"DESeq2\", type=\"binary\")"
Rscript -e  "BiocManager::install(\"VennDiagram\", type=\"source\")"
Rscript -e  "BiocManager::install(\"Rcpp\", type=\"source\")"
Rscript -e  "BiocManager::install(\"apeglm\", type=\"source\")"
Rscript -e  "BiocManager::install(\"ashr\", type=\"source\")"
Rscript -e  "BiocManager::install(\"WGCNA\", type=\"source\")"
Rscript -e  "BiocManager::install(\"cluster\", type=\"source\")"
Rscript -e  "BiocManager::install(\"pheatmap\", type=\"source\")"
Rscript -e  "BiocManager::install(\"jsonlite\", type=\"source\")"
Rscript -e  "BiocManager::install(\"ggplot2\", type=\"source\")"
Rscript -e  "BiocManager::install(\"ggfortify\", type=\"source\")"
Rscript -e  "BiocManager::install(\"limma\", type=\"source\")"
Rscript -e  "install.packages(\"aws.s3\", repos=\"https://cloud.r-project.org/\")"


